name             'opsworks-beaver'
maintainer       'James Brook'
maintainer_email 'james@spaaza.com'
license          'Apache 2.0'
description      'Installs/Configures opsworks-beaver'
long_description 'Installs/Configures opsworks-beaver'
version          '0.1.0'

depends 'python'
depends 'logrotate'
